name: Generar Animacion Snake

on:
  # Se ejecuta automáticamente cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite ejecutar el script manualmente desde la pestaña Actions
  workflow_dispatch:
  # Se ejecuta cada vez que haces un cambio en la rama principal
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generar github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Subir a la rama output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
